### ISSUE TITLE
RSpec/ExpectChange doesn't work well with nested class

### ISSUE THREAD

**Issue by YusukeIwaki** [rubocop/rubocop-rspec#1037]
We use `RSpec/ExpectChange` with `EnforcedStyle: block`.

This rule works well with not nested class like below:

```
it 'should create new token' do
  expect { subject }.to change(Token, :count).by(1)
end
```

But when we use nested class like `User::Token` instead of `Token`,  this rule doesn't work.
It can be easily reproduced with spec/rubocop/cop/rspec/expect_change_spec.rb.

```
Failures:

  1) RuboCop::Cop::RSpec::ExpectChange with EnforcedStyle `block` flags implicit block expectation syntax with nested class
     Failure/Error: super
     
       Diff:
       @@ -1,5 +1,4 @@
                it do
                  expect(run).to change(User::Token, :count).by(1)
       -                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Prefer `change { User::Token.count }`.
                end
       
     # ./spec/support/expect_offense.rb:13:in `expect_offense'
     # ./spec/rubocop/cop/rspec/expect_change_spec.rb:103:in `block (3 levels) in <top (required)>'
```

**Comment by YusukeIwaki** [comment]
ruby-parse shows AST like below for `expect { subject }.to change(User::Token, :count).by(1)`

```
                (send
                  (block
                    (send nil :expect)
                    (args)
                    (send nil :subject)) :to
                  (send
                    (send nil :change
                      (const
                        (const nil :User) :Token)
                      (sym :count)) :by
                    (int 1))))))))
```

RSpec::ExpectChange checks the AST with regex `(send nil? :change ({const send} nil? $_) (sym $_))`, however it doesn't match with

```
                      (const
                        (const nil :User) :Token)
```

**Comment by pirj** [comment]
Would you like to turn the changes from the above comment into a pull request and throw in a couple of tests, @YusukeIwaki ?

**Comment by YusukeIwaki** [comment]
@pirj Thank you for your kind advice, I will try it.
