### ISSUE TITLE
`RSpec/FactoryBot/CreateList` fails to parse `10.times {}`

### ISSUE THREAD

**Issue by hosamaly** [rubocop/rubocop-rspec#1284]
Using Rubocop 1.30.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.5 x86_64-darwin20)

Given a file with the following code:
```ruby
# rubocop:disable all
# rubocop:enable RSpec/FactoryBot/CreateList
10.times {}
```

We see the following error:
```
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /Users/hosamaly/monorepo/commons-ruby/boardintelligence-rails/x_spec.rb:3:0.
  undefined method `block_type?' for nil:NilClass
rubocop-rspec-2.10.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:79:in `contains_only_factory?'
rubocop-rspec-2.10.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:58:in `on_block'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:98:in `each'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:69:in `on_block'
rubocop-ast-1.18.0/lib/rubocop/ast/traversal.rb:20:in `walk'
...
```

**Comment by pirj** [comment]
Thanks for reporting, @hosamaly 
Just out of curiosity, how such code is used?

**Comment by hosamaly** [comment]
I'm not sure about its purpose, but it was part of a project that I worked on once.

Thanks for the quick fix :)
