### ISSUE TITLE
An error occurred while RSpec/Rails/InferredSpecType cop was inspecting ... (2.14.0)

### ISSUE THREAD

**Issue by doconnor-clintel** [rubocop/rubocop-rspec#1429]
I believe this was happier under rubocop-rspec 2.13.0.

Running:
```
clintel@clintel-VirtualBox:~/Clintel/careright$ bundle exec rubocop -d spec/requests/appointments_controller_spec.rb
```
Produces:
```
For /home/clintel/Clintel/careright: configuration from /home/clintel/Clintel/careright/.rubocop.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-performance-1.15.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-performance-1.15.0/config/default.yml
Default configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rails-2.17.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rails-2.17.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rspec-2.14.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rspec-2.14.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rake-0.6.0/config/default.yml
Inheriting configuration from /home/clintel/Clintel/careright/.rubocop_todo.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /home/clintel/Clintel/careright/spec/requests/appointments_controller_spec.rb
An error occurred while RSpec/Rails/InferredSpecType cop was inspecting /home/clintel/Clintel/careright/spec/requests/appointments_controller_spec.rb:3:0.
undefined method `location' for nil:NilClass
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rspec-2.14.0/lib/rubocop/cop/rspec/rails/inferred_spec_type.rb:94:in `autocorrect'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rspec-2.14.0/lib/rubocop/cop/rspec/rails/inferred_spec_type.rb:69:in `block in on_block'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/base.rb:346:in `correct'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/base.rb:127:in `add_offense'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-rspec-2.14.0/lib/rubocop/cop/rspec/rails/inferred_spec_type.rb:68:in `on_block'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:69:in `on_block'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:136:in `each'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:286:in `loop'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:138:in `block in file_offenses'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:163:in `file_offense_cache'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:137:in `file_offenses'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:128:in `process_file'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:108:in `each'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:108:in `reduce'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:108:in `each_inspected_file'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:94:in `inspect_files'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/runner.rb:47:in `run'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli/command.rb:11:in `run'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:72:in `run_command'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:79:in `execute_runners'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/lib/rubocop/cli.rb:48:in `run'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/exe/rubocop:19:in `block in <top (required)>'
/usr/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/gems/rubocop-1.37.0/exe/rubocop:19:in `<top (required)>'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/bin/rubocop:23:in `load'
/home/clintel/Clintel/careright/.bundle/ruby/2.6.0/bin/rubocop:23:in `<main>'
C

Offenses:

spec/requests/appointments_controller_spec.rb:3:26: C: [Correctable] RSpec/SortMetadata: Sort metadata alphabetically.
describe "Appointments", type: :request, data_producer_helpers: true do
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/requests/appointments_controller_spec.rb:53:23: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
      calendar_view = create :calendar_view, providers: [p1, p2]
                      ^^^^^^
spec/requests/appointments_controller_spec.rb:184:20: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        patient1 = create :patient
                   ^^^^^^
spec/requests/appointments_controller_spec.rb:185:20: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        patient2 = create :patient
                   ^^^^^^
spec/requests/appointments_controller_spec.rb:186:18: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        alert1 = create :alert, patient_id: apt1.patient.id
                 ^^^^^^
spec/requests/appointments_controller_spec.rb:188:18: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        alert2 = create :alert, patient_id: patient2.id
                 ^^^^^^

1 file inspected, 6 offenses detected, 6 offenses autocorrectable

1 error occurred:
An error occurred while RSpec/Rails/InferredSpecType cop was inspecting /home/clintel/Clintel/careright/spec/requests/appointments_controller_spec.rb:3:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.37.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.6.6) [x86_64-linux-gnu]
Finished in 1.223285329004284 seconds
```

Recently added cop; offending line:
https://github.com/rubocop/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/rails/inferred_spec_type.rb#L94

Code being assessed:
```
require "spec_helper"

describe "Appointments", type: :request, data_producer_helpers: true do
  before do
    ....
```

**Comment by pirj** [comment]
Thanks for reporting.
Can you please try with `rubocop-rspec` from `master` to see if it has resolved the issue?

**Comment by bquorning** [comment]
v2.14.1 is released with (hopefully) a fix. Thank you for reporting this issue.

**Comment by doconnor-clintel** [comment]
Seems happier:
```
-    rubocop-rspec (2.14.0)
+    rubocop-rspec (2.14.1)
```

```
clintel@clintel-VirtualBox:~/Clintel/careright$ bundle exec rubocop spec/requests/appointments_controller_spec.rb
Inspecting 1 file
C

Offenses:

spec/requests/appointments_controller_spec.rb:3:26: C: [Correctable] RSpec/Rails/InferredSpecType: Remove redundant spec type.
describe "Appointments", type: :request, data_producer_helpers: true do
                         ^^^^^^^^^^^^^^
spec/requests/appointments_controller_spec.rb:3:26: C: [Correctable] RSpec/SortMetadata: Sort metadata alphabetically.
describe "Appointments", type: :request, data_producer_helpers: true do
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/requests/appointments_controller_spec.rb:53:23: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
      calendar_view = create :calendar_view, providers: [p1, p2]
                      ^^^^^^
spec/requests/appointments_controller_spec.rb:184:20: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        patient1 = create :patient
                   ^^^^^^
spec/requests/appointments_controller_spec.rb:185:20: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        patient2 = create :patient
                   ^^^^^^
spec/requests/appointments_controller_spec.rb:186:18: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        alert1 = create :alert, patient_id: apt1.patient.id
                 ^^^^^^
spec/requests/appointments_controller_spec.rb:188:18: C: [Correctable] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
        alert2 = create :alert, patient_id: patient2.id
                 ^^^^^^

1 file inspected, 7 offenses detected, 7 offenses autocorrectable

```

**Comment by ydah** [comment]
Thank you very much for your report!
