### ISSUE TITLE
Infinite loop caused by RSpec/ExampleWording

### ISSUE THREAD

**Issue by luismoyano** [rubocop/rubocop-rspec#1433]
Hello! Just wanted to let you know guys that today got updated to the latest version and the new cop for `RSpec/ExampleWording` seems to be giving infinite loops

rubocop-rspec version: 1.36.0

The issue seems to be coming from #1350

For the command `bundle exec rubocop -a`

running on a test like this:

```
it "works" do
  do_stuff
  expect(stuff).to have_been_done
end
```

Here's the logs

```
spec/services/[such_censored]/[so_confidential]/[very_anonymized]_spec.rb:18:13: C: [Corrected] RSpec/ExampleWording: Your example description is insufficient.
        it "works" do
            ^^^^^

585 files inspected, 23 offenses detected, 1 offense corrected, 22 more offenses can be corrected with `rubocop -A`
Infinite loop detected in /Users/luis/repo/canua/spec/services/[such_censored]/[so_confidential]/[very_anonymized]_spec.rb and caused by RSpec/ExampleWording
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:304:in `check_for_infinite_loop'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:286:in `loop'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:138:in `block in file_offenses'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:163:in `file_offense_cache'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:137:in `file_offenses'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:128:in `process_file'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:108:in `each'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:108:in `reduce'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:108:in `each_inspected_file'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:94:in `inspect_files'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:47:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli.rb:72:in `run_command'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli.rb:79:in `execute_runners'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/lib/rubocop/cli.rb:48:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/exe/rubocop:19:in `block in <top (required)>'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.36.0/exe/rubocop:19:in `<top (required)>'
/Users/luis/.rbenv/versions/3.1.0/bin/rubocop:25:in `load'
/Users/luis/.rbenv/versions/3.1.0/bin/rubocop:25:in `<top (required)>'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/luis/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
/Users/luis/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
/Users/luis/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'

```

**Comment by ydah** [comment]
@akrox58 This is just FYI.
The minimum reproduction procedure is to run rubocop with the following code under spec.

```ruby
it 'works' do
end
```

It looks to me @pirj hypothesis is probably the right one.

**Comment by pirj** [comment]
@luismoyano Can you please check if #1438 fixes your case?
