### ISSUE TITLE
Infinite loop caused by RSpec/FactoryBot/ConsistentParenthesesStyle

### ISSUE THREAD

**Issue by salcudeann** [rubocop/rubocop-rspec#1458]
Hey, after upgrading to the latest version (`2.14.2`) a cop is causing an infinite loop and rubocop crashes when trying to run.

For the command `bundle exec rubocop -a`.

Running on a test like this:

```
        it 'returns default bucket if specified' do
          build

          expect(stuff).to eq 'a'
        end
```

And here we have the logs:
`Infinite loop detected in //location and caused by RSpec/FactoryBot/ConsistentParenthesesStyle -> Style/MethodCallWithoutArgsParentheses`

**Comment by ydah** [comment]
Thank you for your report.
I have tried, but the code you have provided does not seem to reproduce the problem.

Can you please provide us with the results of your .rubocop.yml and `rubocop -V`?

I checked the following environment:
```
bundle exec rubocop -V                                                                                                              
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.7.2) [x86_64-darwin21]
  - rubocop-performance 1.15.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.14.2
```

**Comment by salcudeann** [comment]
`rubocop -V` returns the following:
```
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-linux]
  - rubocop-performance 1.15.0
  - rubocop-rspec 2.14.2
```
In `.rubocop.yml` besides disabling a few cops I have the following settings for all cops:
```
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.1.2
  UseCache: true
  MaxFilesInCache: 15000
```

**Comment by ydah** [comment]
I was able to reproduce it. Thank you very much.
(Apparently it was a problem with my environment. Sorry.)

```
bundle exec rubocop spec/factories.rb -a
Inspecting 1 file
C

Offenses:

spec/factories.rb:4:3: C: [Corrected] RSpec/FactoryBot/ConsistentParenthesesStyle: Prefer method call with parentheses
  build
  ^^^^^
spec/factories.rb:4:8: C: [Corrected] Style/MethodCallWithoutArgsParentheses: Do not use parentheses for method calls with no arguments.
  build()
       ^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /ydah/rubocop/spec/factories.rb and caused by RSpec/FactoryBot/ConsistentParenthesesStyle -> Style/MethodCallWithoutArgsParentheses
/ydah/rubocop/lib/rubocop/runner.rb:304:in `check_for_infinite_loop'
/ydah/rubocop/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/ydah/rubocop/lib/rubocop/runner.rb:286:in `loop'
/ydah/rubocop/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/ydah/rubocop/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/ydah/rubocop/lib/rubocop/runner.rb:138:in `block in file_offenses'
/ydah/rubocop/lib/rubocop/runner.rb:163:in `file_offense_cache'
/ydah/rubocop/lib/rubocop/runner.rb:137:in `file_offenses'
/ydah/rubocop/lib/rubocop/runner.rb:128:in `process_file'
/ydah/rubocop/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
/ydah/rubocop/lib/rubocop/runner.rb:108:in `each'
/ydah/rubocop/lib/rubocop/runner.rb:108:in `reduce'
/ydah/rubocop/lib/rubocop/runner.rb:108:in `each_inspected_file'
/ydah/rubocop/lib/rubocop/runner.rb:94:in `inspect_files'
/ydah/rubocop/lib/rubocop/runner.rb:47:in `run'
/ydah/rubocop/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
:
``

**Comment by ydah** [comment]
Ah, I finally understand.
The following Pull Request was corrected this issue.
- https://github.com/rubocop/rubocop-rspec/pull/1446

Please wait for the next release.

**Comment by salcudeann** [comment]
Sounds great, thanks!
