### ISSUE TITLE
RSpec/ChangeByZero cop and compound operators

### ISSUE THREAD

**Issue by twelve17** [rubocop/rubocop-rspec#1471]
Hello,

I see that there was an issue with this use case that was fixed in #1324 and [released in 2.13.0](https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2130-2022-09-12) . However, I ran into the following error even after updating to `2.15.0`:

```
An error occurred while RSpec/ChangeByZero cop was inspecting ...foo.../xyz_spec.rb:90:54.
undefined method `method_name' for #<RuboCop::AST::AndNode:0x000000015aceea18>
Did you mean?  method
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-rspec-2.15.0/lib/rubocop/cop/rspec/change_by_zero.rb:115:in `compound_expectations?'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-rspec-2.15.0/lib/rubocop/cop/rspec/change_by_zero.rb:103:in `check_offense'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-rspec-2.15.0/lib/rubocop/cop/rspec/change_by_zero.rb:91:in `block in on_send'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-rspec-2.15.0/lib/rubocop/cop/rspec/change_by_zero.rb:82:in `expect_change_with_arguments'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-rspec-2.15.0/lib/rubocop/cop/rspec/change_by_zero.rb:90:in `on_send'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:136:in `public_send'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:136:in `block (2 levels) in trigger_restricted_cops'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:135:in `block in trigger_restricted_cops'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:134:in `each'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:134:in `trigger_restricted_cops'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-1.38.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:158:in `block in on_send'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `each'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `each_with_index'
...foo.../.rvm/gems/ruby-2.7.6/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `on_send'
```

The spec causing this error has the following expectation:

```
expect {
  method_being_tested
}.to change(ModelA, :count).by(-1).and change(ModelB, :count).by(0)
```

Additional version info:
```
1.38.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.7.6) [arm64-darwin21]
```

**Comment by twelve17** [comment]
My mistake, the spec had a typo in it. It had:

`.to change(ModelA, :count).by(-1) and`

instead of

`.to change(ModelA, :count).by(-1).and`

(Missing dot before `and`)

**Comment by ydah** [comment]
Thank you for your report.
Please let us know if you notice anything else.
