### ISSUE TITLE
Facing `SystemStackError` on alpine dockers

### ISSUE THREAD

**Issue by houdinisparks** [rubocop/rubocop-rspec#1797]
Related to https://github.com/rubocop/rubocop-rspec/issues/665, but posting a new issue as the previous one is closed and did not have a helpful answer.

Versions:

```bash
/ # ruby --version
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux-musl]
/ # bundle --version
Bundler version 2.4.6
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.3
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
/
/ # docker --version
Docker version 23.0.6, build ef23cbc
/ # 

```

```
$ bundle exec rubocop
bundler: failed to load command: rubocop (/builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/bin/rubocop)
/builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:25:in `each': stack level too deep (SystemStackError)
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:25:in `each_child_node'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/lib/rubocop/rspec/example_group.rb:51:in `each'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/lib/rubocop/rspec/example_group.rb:51:in `flat_map'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/lib/rubocop/rspec/example_group.rb:51:in `find_all_in_scope'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/lib/rubocop/rspec/example_group.rb:62:in `find_all'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/lib/rubocop/rspec/example_group.rb:52:in `block in find_all_in_scope'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:28:in `block in each_child_node'
	from /builds/wog/gvt/grants-portal-team/grants/formflow/formflow-mono/packages/app/vendor/bundle/ruby/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/node/mixin/descendence.rb:25:in `each'
	 ... 251 levels...
	from /usr/local/rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
	from /usr/local/rbenv/versions/3.2.1/bin/bundle:25:in `load'
	from /usr/local/rbenv/versions/3.2.1/bin/bundle:25:in `<main>'
Inspecting 453 files
.............................................................................................................................................................................................................................................................................................................................................................................................................................
412 files inspected, no offenses detected
```

Setting these env vars to increase te stack thread size does not help either:

```bash
$ export PTHREAD_STACK_MIN=8388608
$ export RUBY_THREAD_MACHINE_STACK_SIZE=8388608
$ export RUBY_THREAD_VM_STACK_SIZE=8388608

$ ruby -ve 'p RubyVM::DEFAULT_PARAMS'
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux-musl]
{:thread_vm_stack_size=>8388608, :thread_machine_stack_size=>8388608, :fiber_vm_stack_size=>131072, :fiber_machine_stack_size=>524288}

$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 125107
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

Any ideas?

**Comment by pirj** [comment]
Please provide the code to reproduce the problem in the original issue, and we’ll reopen it.
No need for duplicates.
