### ISSUE TITLE
`bundle exec erblint` is throwing error `cannot load such file -- rubocop/rspec/language/node_pattern (LoadError)`

### ISSUE THREAD

**Issue by arinchoi03** [rubocop/rubocop-rspec#1934]
we are upgrading to rubocop 3.0.2 from 2.31.0 and ran into multiple issues while upgrading. Would love some guidance on what I should do to remediate.

Here's what I have so far:
in `.rubocop.yml`
```
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara
```

Gemfile
```
group :development, :test do
  gem 'rspec-rails'
  gem 'rubocop-capybara', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-rspec_rails', require: false
end

group :development do
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end
```

I first ran into this error when I ran `bundle exec rubocop` _locally_ so I ran that with the [`--restart-server` option as reported here](https://github.com/rubocop/rubocop/issues/13003#issuecomment-2175480112).
This passed the rubocop locally but started failing with the same error on our CircleCI run of `bundle exec rubocop`, so I updated `.circleci/config.yml` file to run `bundle exec rubocop --restart server` as well, which then led to other checks failing which used the `bundle exec rake db:test:prepare` command, with the same error `cannot load such file -- rubocop/rspec/language/node_pattern (LoadError)`. 

Then I _removed_ the `--restart-server` from the `circleci/config.yml` file and now `bundle exec rubocop`, `bundle exec rake db:test:prepare` are running without error.

However the last remaining issue is our `bundle exec erblint app/views` command, which is failing locally and on circle ci with the same error. Is there a way to resolve this?

-- 
backtrace from circle ci run of `bundle exec erblint app/views`:

```
warning: parser/current is loading parser/ruby31, which recognizes 3.1.6-compliant syntax, but you are running 3.1.4.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Linting 462 files with 12 linters...
bundler: failed to load command: erblint (/home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/bin/erblint)
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- rubocop/rspec/language/node_pattern (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/circleci/redacted/vendor/bundle/ruby/3.1.0/gems/rubocop-rspec_rails-2.29.0/lib/rubocop-rspec_rails.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:35:in `load'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
        from <internal:kernel>:90:in `tap'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:52:in `load_file'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:214:in `block in base_configs'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:213:in `map'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:213:in `base_configs'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:21:in `resolve_inheritance'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:57:in `load_file'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/linters/rubocop.rb:175:in `config_from_path'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/linters/rubocop.rb:170:in `block in config_from_hash'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/linters/rubocop.rb:129:in `block in tempfile_from'
        from /usr/local/lib/ruby/3.1.0/tempfile.rb:358:in `create'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/linters/rubocop.rb:125:in `tempfile_from'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/linters/rubocop.rb:169:in `config_from_hash'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/linters/rubocop.rb:29:in `initialize'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/runner.rb:17:in `new'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/runner.rb:17:in `block in initialize'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/runner.rb:16:in `map'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/runner.rb:16:in `initialize'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/cli.rb:80:in `new'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/lib/erb_lint/cli.rb:80:in `run'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/gems/erb_lint-0.5.0/exe/erblint:9:in `<top (required)>'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/bin/erblint:25:in `load'
        from /home/circleci/REDACTED/vendor/bundle/ruby/3.1.0/bin/erblint:25:in `<top (required)>'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /home/circleci/.rubygems/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
        from /home/circleci/.rubygems/bin/bundle:25:in `load'
        from /home/circleci/.rubygems/bin/bundle:25:in `<main>'

Exited with code exit status 1
```

**Comment by pirj** [comment]
Hi!
Can you please provide a backtrace?

**Comment by arinchoi03** [comment]
@pirj of course! updated the description with backtrace

**Comment by pirj** [comment]
You have to update `rubocop-rspec_rails` to [2.30.0](https://github.com/rubocop/rubocop-rspec_rails/blob/master/CHANGELOG.md#2300-2024-06-12) that has [the fix](https://github.com/rubocop/rubocop-rspec_rails/pull/30).
Please accept my apologies for the inconvenience.

**Comment by arinchoi03** [comment]
@pirj thank you x1000000! Updating the gem worked for me 🙏
